# Generated by Django 5.2.4 on 2025-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="authority",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
