# Generated by Django 5.2.4 on 2025-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_cart_cartitem_cart_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="unpaid", max_length=50),
        ),
    ]
